services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  # redis:
  #   image: 'redis:3.2.0'
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - ./data/redis:/data:z