# Generated by Django 3.2.13 on 2022-04-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0005_notification_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaingn_id', models.CharField(max_length=8)),
                ('campaingn_cost', models.CharField(max_length=8)),
                ('user_id', models.CharField(max_length=8)),
            ],
        ),
    ]
