# Generated by Django 3.2.13 on 2022-04-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0006_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='campaingn_cost',
            field=models.FloatField(),
        ),
    ]
