# Generated by Django 3.2.13 on 2022-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0007_alter_transaction_campaingn_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsapiaccesstoken',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
    ]
