# Generated by Django 3.2.13 on 2022-04-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0009_schedulegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
