# Generated by Django 3.2.13 on 2022-04-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0010_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
