# Generated by Django 3.2.13 on 2022-04-27 08:42

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0011_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcc', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None)),
                ('feeders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '23456789'. Up to 9 digits allowed.", regex='/^\\d{9}$/')])),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('CC1', 'CC1')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedulegroup',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='schedulegroup',
            name='group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), size=None),
        ),
    ]
