# Generated by Django 3.2.13 on 2022-04-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0012_auto_20220427_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=10)),
                ('message', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightsoff.schedulegroup')),
                ('subscriber', models.ManyToManyField(to='lightsoff.Subscriber')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightsoff.transaction')),
            ],
        ),
    ]
