# Generated by Django 3.2.13 on 2022-04-27 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0014_alter_schedulegroup_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedulegroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='place',
            name='groups',
        ),
        migrations.AddField(
            model_name='schedulegroup',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lightsoff.groupname'),
        ),
        migrations.AddField(
            model_name='place',
            name='groups',
            field=models.ManyToManyField(to='lightsoff.GroupName'),
        ),
    ]
