# Generated by Django 3.2.13 on 2022-04-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('lightsoff', '0015_auto_20220427_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulegroup',
            name='periodic_task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
