# Generated by Django 3.2.13 on 2022-04-28 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0017_auto_20220427_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='mobile_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '23456789'. Up to 9 digits allowed.", regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='campaingn_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='campaingn_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
