# Generated by Django 3.2.13 on 2022-04-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0019_auto_20220428_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
