# Generated by Django 3.2.13 on 2022-04-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0020_auto_20220428_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
