# Generated by Django 3.2.13 on 2022-04-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0021_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightsoff.groupname'),
        ),
    ]
