# Generated by Django 3.2.13 on 2022-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0022_alter_subscriber_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
