# Generated by Django 3.2.13 on 2022-05-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0023_transaction_tx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProcessedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_id', models.CharField(max_length=150)),
            ],
        ),
    ]
