# Generated by Django 3.2.13 on 2022-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0024_lastprocesseddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='gcc',
            field=models.TextField(),
        ),
    ]
