# Generated by Django 3.2.13 on 2022-05-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0025_auto_20220502_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulegroup',
            name='periodic_task',
        ),
    ]
