# Generated by Django 3.2.13 on 2022-05-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0026_remove_schedulegroup_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_batch_run',
            field=models.BooleanField(default=False),
        ),
    ]
