# Generated by Django 3.2.13 on 2022-05-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0028_transaction_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='gcc',
            new_name='gss',
        ),
    ]
