# Generated by Django 3.2.13 on 2022-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0029_rename_gcc_place_gss'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuburbPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gss', models.TextField()),
                ('area', models.TextField()),
                ('suburb', models.TextField()),
            ],
        ),
    ]
