# Generated by Django 3.2.13 on 2022-05-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightsoff', '0030_suburbplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='suburb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
